name: Run hltvMatchFetcher.ts every hour

on:
  schedule:
  - cron: '0 * * * *'  # Run every hour

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Use Node.js version 14

    - name: Install dependencies
      run: npm install

    - name: Compile TypeScript
      run: tsc hltvMatchFetcher.ts --outDir ./lib

    - name: Run script
      run: node ./lib/hltvMatchFetcher.js  # Adjust this path based on where the JS file gets generated
      env:
        AZURE_ACCOUNT_NAME: ${{ secrets.AZURE_ACCOUNT_NAME }}
        AZURE_ACCOUNT_KEY: ${{ secrets.AZURE_ACCOUNT_KEY }}
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
